apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: todo-backend
  namespace: default
spec:
  selector:
    app: todo-backend
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 8082
