apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo-frontend
  namespace: default
  labels:
    app:  todo-frontend
spec:
  selector:
    matchLabels:
      app: todo-frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: adamako/todo-frontend:latest
        resources:
          requests:
            cpu: 300m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 100Mi
        env:
          - name: REACT_APP_API_URL
            value: http://192.168.59.100:30886
        ports:
        - containerPort:  3000
          name:  todo-frontend
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend-config
  labels:
    app: todo-frontend
  namespace: default
data:
  REACT_APP_API_URL: http://backend-service
  
