apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres
  namespace: default
  labels:
    app:  postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  postgres
    spec:
      containers:
      - name:  postgres
        image:  postgres
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  labels: 
    app: postgres
  namespace: default
data:
  POSTGRES_DB: kotlinTodo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: zuhelfnfahwd
